### ISSUE TITLE
Pathfinder 2 issues

### ISSUE THREAD

**Issue by Weissrolf** [caewok/fvtt-walled-templates#10]
Hello.

There are two issues I am experiencing:

1. Not compatible with "PF2e TokenMagic Integration" module, which disables walled templates when both are loaded (walls are ignored then).

2. Unfortunately I am not able to create PF2e compatible templates with Walled Templates. Different area settings fit different template shapes and sizes.

**Comment by Weissrolf** [comment]
There also is the libwrapper conflict message when Walled Templates is run in combination with Token Magic FX with or without the PF2e integration module. So the

"libWrapper: Potential conflict detected between module Walled Templates and module Token Magic FX.
Module walledtemplates did not chain the wrapper for 'MeasuredTemplate.prototype.refresh'."

**Comment by caewok** [comment]
PF2e TokenMagic Integration does not use libWrapper, so there is not much I can do on my end to ensure compatibility. I am happy to try to coordinate with that author if I can.

I will close this for now, as I am not sure if your issue #2 is a separate issue or not. If it is separate, please feel free to add a comment with some details or screen shots of what you are seeing with template shapes and sizes. Thanks!
