### ISSUE TITLE
Feature Request: Make template.targetsWithingShape always avaialble.

### ISSUE THREAD

**Issue by tposney** [caewok/fvtt-walled-templates#104]
In previous versions of walled templates, template.targetsWithinShape was available even if auto targeting was disabled. Currently it seems to only be available if auto targeting is enabled.

In midi I call this directly to juggle between different template targeting strategies, some using walled templates and some not, which means generally having walled templates auto targeting disabled.

It would be great if that was available again.
Thanks

**Comment by caewok** [comment]
Added in v0.7.7.
