### ISSUE TITLE
[Feature Request] Better control over who is targeted (i.e. don't target dead/hidden)

### ISSUE THREAD

**Issue by morepurplemorebetter** [caewok/fvtt-walled-templates#108]
As it stands, I'm still using Midi-QoL's targetting and not Walled Template's because with Midi I can set to not target Dead tokens, it will ignore hidden tokens, and it will ignore tokens with `flags.midi-qol.neverTarget` (e.g. used for spiritual weapon tokens).

Adding this same functionality by default or as an option to Walled Templates would be a great addition IMHO.

**Comment by caewok** [comment]
Walled Templates should already respect the `flags.midi-qol.neverTarget` flag. I might add a setting to not target dead tokens, so leaving this issue open for that.

**Comment by caewok** [comment]
I added `CONFIG.walledtemplates.autotargetStatusesToIgnore` in v0.7.9. It defines a set, which of course you can modify via macro or world script, of status ids that autotarget should ignore. I made "dead" the only status to be ignored by default, as that seemed a (relatively) safe choice. Between that and the midiqol flag, that should give you decent options. You could even define one or more special "ignore_targeting" settings that you could apply manually or automatically (via macro or active effects) to tokens.

**Comment by morepurplemorebetter** [comment]
Thank you very much for implementing this!
