### ISSUE TITLE
Feature: Add snap-to-center as option and set snapping per-template shape

### ISSUE THREAD

**Issue by caewok** [caewok/fvtt-walled-templates#116]
https://ptb.discord.com/channels/915186263609454632/1167221795103985764/1241078330476986499

**Comment by Ikabodo** [comment]
A few thoughts on this, if you ever have the time to look into this. Current 5e default behavior snaps to intersections or centers. That works pretty well if you tell players to place them right. 

So anything above that would be a new feature. Here are my thoughts on it.

* Add an option to set snapping per template, this makes it flexible. Some spells might need snapping, others not. And different snapping types.
 - Snap to intersection only (shift to override)
 - Snap to center of line only (shift to override)
 - Snap to center only (shift to override) 
* Add option to set default per square, ray and so on. Like the other defaults. This way you can force squares to be intersections, and leave rays for example.


Bonus thought:
 - Snap to source token
_Mostly for breath attack like spells. The template is auto placed on the token, then the player rotates the mouse to place the template with a click. _

**Comment by caewok** [comment]
Added in v0.8.2
