### ISSUE TITLE
Templates attached to tokens dont change elevation

### ISSUE THREAD

**Issue by strongpauly** [caewok/fvtt-walled-templates#123]
If a template is attached to a token, and that token's elevation changes, the templates elevation is not changed to match.  I would assume it would move in the Z axis in the same way it moves in X and Y.

Foundry: v12.328
D&D5e: v3.2.1
Walled Template: v0.8.0
libWrapper: v1.12.13.1

**Comment by caewok** [comment]
It used to, but Foundry v12 broke it. Addressed in v0.8.1.
