### ISSUE TITLE
[Issue] Using Walled Templates means all the templates I use don't show the area they're covering unless selected

### ISSUE THREAD

**Issue by weefreemen** [caewok/fvtt-walled-templates#126]
Using Walled Templates means all the templates I use don't show the area they're covering unless selected, I want to be able to have them on permanently, but, can't see it in the options.

Any ideas?

**Comment by caewok** [comment]
There are several options for this. First, check in the Walled Template module settings. You want "hide template border" and "hide template highlighting" disabled. 

Second, any given template can be modified using the Walled Templates tab in the config for that template. For dnd5e, you will also want to check a given spell, where again there is a Walled Templates tab to show/hide templates for specific spells.

The template and dnd5e spell configs default to being controlled by the module settings, so typically you should not have to change those.

**Comment by weefreemen** [comment]
Hey,

Sorry for not coming back to this, it turned out to be a big with, uh I
think FX Master due to it being outdated, but it was causing a conflict,
not sure if it's fixed now, I imagine it should be

Appreciate you coming back to me!
