### ISSUE TITLE
Wall template stops damage being rolled

### ISSUE THREAD

**Issue by Stonedtroll** [caewok/fvtt-walled-templates#127]
Getting these errors

![image](https://github.com/user-attachments/assets/de9b0aec-4cf5-431b-99b0-4c3219876aa6)

![image](https://github.com/user-attachments/assets/255cd97c-ea0f-4caf-a099-04f6cf6c2211)

![image](https://github.com/user-attachments/assets/f6f0f08f-bd2c-4e2a-a13c-9dfd299a012f)

![image](https://github.com/user-attachments/assets/14b349be-cc0e-49fe-b282-f56d8783f852)

Disabling the module permits damage to be rolled.

**Comment by caewok** [comment]
I added a check for whether `actor.statuses` is defined in v0.8.1. Not sure why it would not be, but maybe that will help.
