### ISSUE TITLE
[D&D5e 4.0.x] Item Sheet Tab Missing

### ISSUE THREAD

**Issue by hakr14** [caewok/fvtt-walled-templates#128]
In version 4.0.0, the D&D5e system introduced a new item sheet to accommodate a new feature called [Activities](https://github.com/foundryvtt/dnd5e/wiki/Activities). This new sheet does not feature the Walled Templates tab.
3.3.1:
![3.3.1](https://github.com/user-attachments/assets/2f5135f9-99f9-4b6d-ace9-dd0504644f52)
4.0.2:
![4.0.2](https://github.com/user-attachments/assets/8990953f-5b2a-402f-9450-049988d2e207)
While the rest of the module works fine, the item tab sheet allowed certain spells or items to behave differently from the default. Without it, this is only possible by editing the template directly after placing.

#### Suggestion:
Perhaps the Walled Template settings could instead be per activity, allowing for a single spell to behave differently depending on the activity chosen. The tab would be best placed under the Activation section, along with Targeting.
![activity](https://github.com/user-attachments/assets/356c0949-9ce9-4a77-9f93-f25f9c43ab39)

**Comment by caewok** [comment]
Addressed in v0.8.1. Not sure yet if it should be per activity. Probably, but it would mean a whole other set of overrides. We already have:
1. Module template settings.
2. Per-spell settings.
3. Per-template config settings.

Let's see if there is a strong use case for it before I start digging into how to add things to the activity templates.
