### ISSUE TITLE
Template is throwing errors and not auto targeting.

### ISSUE THREAD

**Issue by Stonedtroll** [caewok/fvtt-walled-templates#132]
I believe it was working with DND5e 4.1.1 but cannot say that 4.1.2 is the cause.

![image](https://github.com/user-attachments/assets/1ca9bc66-144e-49df-8f5e-5bec081e23dc)

System: DND5e 4.1.2
Foundry: 12.331

**Comment by caewok** [comment]
Do any of the tokens on your scene not have actors? You can find out by double-clicking a token to open its sheet. If the token is linked to an actor that no longer exists, Foundry will throw an error instead of opening the sheet.

**Comment by Stonedtroll** [comment]
That must be it as I can no longer reproduce the error. Apologies for the inconvenience.
