### ISSUE TITLE
Player template changes GM targeting

### ISSUE THREAD

**Issue by caewok** [caewok/fvtt-walled-templates#14]
https://ptb.discord.com/channels/170995199584108546/722566083499786352/1029705248790548530

When a player creates a template with autotargeting, the GM's targets change.

**Comment by thatlonelybugbear** [comment]
It also needs the GM to have autotargeting on.
So it seems that there might be a check missing if the template is created
on a different client that the GM's or something!

**Comment by caewok** [comment]
Fixed in v0.4.4.
