### ISSUE TITLE
error children undefined during init

### ISSUE THREAD

**Issue by eheliot2** [caewok/fvtt-walled-templates#18]
after migration to v10
system : homemade manifest if necesseray https://arsdd.artaneb.fr/foundryvtt/system/system.json

Uncaught (in promise) TypeError: Cannot read properties of null (reading 'children')
[Detected 1 package: walledtemplates]
    at Object.fn (module.js:101:28)
    at #call (foundry.js:724:20)
    at Hooks.callAll (foundry.js:681:17)
    at Game.setupGame (foundry.js:7909:11)
    at async Game._initializeGameView (foundry.js:8954:5)
    at async Game.initialize (foundry.js:7782:5)

with a new world based on the same system : only walled template activated : it's ok
so in the migrated world
* only walled tempalte activated : not ok
* check all the scene to remove template : not ok

**Comment by caewok** [comment]
I cannot replicate in a new world for that system, so I am assuming it has something to do with the migration. In the browser console (F12), are there any templates when you type `canvas.templates.placeables`?

**Comment by eheliot2** [comment]
there is no children

![image](https://user-images.githubusercontent.com/117301263/199844059-fb40dfaa-5c62-4a22-a784-ae47b7d9626b.png)

if it's just migration issue, how can i fix it, maybe directly in db ?
thanks

**Comment by eheliot2** [comment]
nice
it's solved the error : test done
thanks

**Comment by caewok** [comment]
Great!
