### ISSUE TITLE
error during open/close door

### ISSUE THREAD

**Issue by eheliot2** [caewok/fvtt-walled-templates#19]
![image](https://user-images.githubusercontent.com/117301263/204137737-166b2c03-275f-41ac-bca2-329f39ae72cd.png)
browser : chrome

![image](https://user-images.githubusercontent.com/117301263/204137691-4eeaa7bd-96ea-44dc-a5ab-a9fdb39bbb4a.png)

in the change, theere is only ds for the door state, c is undefined.

**Comment by weepingminotaur** [comment]
Have encountered the same error.

**Comment by caewok** [comment]
Should be resolved in v0.4.5. Thanks!
