### ISSUE TITLE
Incompatibility with Perfect Vision module

### ISSUE THREAD

**Issue by lucaspicerni** [caewok/fvtt-walled-templates#2]
I'm getting this error when loading scenes:

![image](https://user-images.githubusercontent.com/95550238/167715939-ca54803f-bfb2-4fed-90e5-834bda8655c6.png)

![image](https://user-images.githubusercontent.com/95550238/167716572-4c4ee18a-df33-4dbc-9f8b-9b8274ba0c08.png)

 The incompatibility appears to be with the [Perfect Vision](https://github.com/dev7355608/perfect-vision) module:
 
![image](https://user-images.githubusercontent.com/95550238/167716012-f228b52b-1787-49a7-830e-00a66ed72694.png)

Could you implement compatibility between the modules?

**Comment by caewok** [comment]
Fixed in v 0.2.2.
