### ISSUE TITLE
Errors when creating and moving templates

### ISSUE THREAD

**Issue by kristianserrano** [caewok/fvtt-walled-templates#20]
When creating and moving templates, I'm getting a ton of these errors. I'm using the SWADE system if that matters.

![Screenshot 2022-12-22 at 12 14 14 PM](https://user-images.githubusercontent.com/1796189/209189795-96cfc2fe-a453-4e9f-b97f-53ce14aa77c0.png)

**Comment by V3rotti** [comment]
I get the same errors while using dnd5e.
I can not switch back from the measuring controls to token controls; when i do it throws the error again.
Switching scenes throws another error:
![image](https://user-images.githubusercontent.com/56869989/209294540-54943438-4d75-4739-ac65-9a27e5e512eb.png)
the canvas stays black until i disable the mod

**Comment by caewok** [comment]
I pushed a possible fix. Does the `poly.close` is not a function error still occur in v0.4.6?

**Comment by kristianserrano** [comment]
Seems to be working. Thanks for the fix!
