### ISSUE TITLE
Feature Req: Walled Auras

### ISSUE THREAD

**Issue by ckdragons** [caewok/fvtt-walled-templates#21]
Can this module be updated to include token auras?

**Comment by caewok** [comment]
Not sure whether token auras would be a good fit. I see at least two other Foundry modules that take this on: [Token Auras](https://foundryvtt.com/packages/token-auras) and [Active Auras](https://foundryvtt.com/packages/ActiveAuras). What are you looking for that those modules cannot handle?

**Comment by ckdragons** [comment]
I already use Token Auras. What is nice about your module is that templates (not auras) are blocked by walls. Token auras will _bleed_ through walls. If there are similar auras in the adjacent room, then the different aura's will blend together.

**Comment by caewok** [comment]
That is a good point. I will look into a way to lock the template to a token.

**Comment by caewok** [comment]
Have you looked into Token Attacher? https://github.com/KayelGee/token-attacher. It has macros to attach templates to tokens. Probably better than anything I could come up with.

**Comment by ckdragons** [comment]
Thank you. I will look into this.
