### ISSUE TITLE
Feature Request: Options for different blocking with different Restrictions

### ISSUE THREAD

**Issue by Potatozuli** [caewok/fvtt-walled-templates#24]
Currently, it appears as if the only Wall Restriction that this module checks for is Light restriction. If there were options when creating a template to change what restrictions it reads, so it could pass through certain ones but not others, that would be a huge help. For example, if the template is blocked by is Move restrictions, a template would be stopped at a window (having Move restriction but not Light restriction).

**Comment by caewok** [comment]
Yes, this sounds like a good idea.

**Comment by caewok** [comment]
See v0.5.0.
