### ISSUE TITLE
Conflict with Quick Insert?

### ISSUE THREAD

**Issue by FreshnessDND** [caewok/fvtt-walled-templates#25]
Steps to Reproduce...

1. Quick Insert Enabled
2. Walled Templates Enabled
3. Search for something in 'locked' compendia
4. Click to pop out
5. Error (1)

Error does not appear if Walled Templates is disabled.

Tested with no other modules enabled except Libwrapper.

(1)
![image](https://github.com/caewok/fvtt-walled-templates/assets/96202375/efd3ba01-1f4d-4db1-941e-52408d4e06a4)

**Comment by caewok** [comment]
I opened an issue in the [Quick Insert git](https://gitlab.com/fvtt-modules-lab/quick-insert/-/issues/108). I can confirm the error occurs but I do not sufficiently understand it to fix it at the moment.

**Comment by caewok** [comment]
Closing as not fixable without assistance from Quick Insert dev.
