### ISSUE TITLE
Enhancement to handling of global, item and template config

### ISSUE THREAD

**Issue by pgervais70** [caewok/fvtt-walled-templates#27]
Opening an item details tab should not automatically set the walled template properties on the item and the drop down menus should allow an empty choice or default.
The empty choice or default, would allow to take the current global default instead of using the default at the moment the item is opened. 
This would allow changing the default and all the items would inherit the new values unless specific values were set on the item. 

The item or default values would be set on a template flags when it is created. 

Also when evaluating the flag values, the priority should be (from more to less important):
- template
- Item
- Global default 

This would allow a macro to create a template with the proper flags and they would have precedence on the values set on the origin item or global default values. 

Last enhancement, the global config should also allow choose the type of what blocks, instead of forcing light. This is already available on the Item details tab.

**Comment by caewok** [comment]
All good ideas. Implemented in v0.5.2. If you want a macro to create a template that uses global defaults, set the `walledtemplate` flags `wallsBlock = "globalDefault"` or `wallRestriction = "globalDefault"`. Thanks!
