### ISSUE TITLE
Request: Do not target actors marked as NoTarget

### ISSUE THREAD

**Issue by gregpola** [caewok/fvtt-walled-templates#28]
I am using your target logic for templates, but find that it doesn't pay attention to the NoTarget value for "system.details.type.custom". Please add the logic to not target these actors. Thanks!

**Comment by thatlonelybugbear** [comment]
Just to chime in, that key is true for NPC actors, but for PCs you would probably need to use something like `system.details.race.toLocaleLowerCase().includes("notarget")`
