### ISSUE TITLE
Conflict with Perfect-Vision module

### ISSUE THREAD

**Issue by Setting-Dawn** [caewok/fvtt-walled-templates#3]
With only Perfect-Vision and Walled-Templates enabled (and libWrapper) I've encountered some visual rendering issues. I'm not a techy person so I'm sorry I can't really give more than that. I can do my best if you need me to send any more info. 

"Canvas drawing failed for the SightLayer" seems to occur all the time, but things still render
"Canvas drawing failed for the LightingLayer" only seems to occur if there is a light source (on/off doesn't matter), but then this makes the whole scene visually disappear.

Info:
Foundry: v 9 Build 269
DnD5e: v 1.6.1
Walled Templates: v 0.2.0
Perfect-Vision: v 3.9.4
libWrapper: v 1.12.4.0

![Screenshot 2022-05-10 125424](https://user-images.githubusercontent.com/89761215/167720580-de0d1e4f-d30a-4dcd-8a43-4b361299fd1e.png)

![Screenshot 2022-05-10 140433](https://user-images.githubusercontent.com/89761215/167721661-453161b9-64a4-4df6-ae68-ac86ce115780.png)
Some overlap:
![Screenshot 2022-05-10 140451](https://user-images.githubusercontent.com/89761215/167721677-1651f10b-4f79-4fd9-815b-d3c2651093ff.png)

**Comment by Setting-Dawn** [comment]
Overlaps with [ Incompatibility with Perfect Vision module #2 ](https://github.com/caewok/fvtt-walled-templates/issues/2) but this also includes error with LightingLayer which is not included in [#2 ](https://github.com/caewok/fvtt-walled-templates/issues/2)

**Comment by caewok** [comment]
Fixed in v 0.2.2.
