### ISSUE TITLE
Issue with Wall Height

### ISSUE THREAD

**Issue by Wavyisland** [caewok/fvtt-walled-templates#30]
There is an issue when using Walled Templates along with the Wall Height module. If a wall's height is set to less than "infinity" in Wall Height, the templates are not blocked by walls.

**Comment by caewok** [comment]
I have at least temporarily fixed this issue, although I suspect an underlying Wall Height bug. So if Wall Height updates and this crops up again, please let me know. 

Right now, it is treating walled templates as having infinite vertical direction. Walled Templates does not currently let you set the elevation of the template, and neither does Wall Height. Doing so poses some difficulties, depending on how much one cares about mimicing physical characteristics. Like, should circle templates be considered spheres and if so, should the template flow over a wall that is below it? I know Ripper has a module that does 3d templates, and I imagine it is a bit of work!
