### ISSUE TITLE
Feature request: Add additonal never target check to make midi-qol happy

### ISSUE THREAD

**Issue by tposney** [caewok/fvtt-walled-templates#37]
I notice that you already support midi by the check
```js
    if ( getProperty(token, "actor.system.details.type.custom")?.includes("NoTarget") ) return false;
```
I was wondering if you could add
```js
    if ( getProperty(token, "actor.flags.midi-qol.neverTarget") ) return false;
```

**Comment by tposney** [comment]
The noTarget custom type is not a very good solution. I've implemented the flag solution instead and eventually will retire the noTarget check completely

**Comment by caewok** [comment]
Added in v0.6.5.
