### ISSUE TITLE
Configuring attach template to caster when not auto targeting causes odd behaviour

### ISSUE THREAD

**Issue by tposney** [caewok/fvtt-walled-templates#38]
Blank world with dnd5e and walled templates only.
Walled templates configured to NOT auto target.
Fireball spell configured to attach template to  caster.
Once cast attempting to move the caster token causes the template to be selected and cannot be unselected without world reload.

**Comment by caewok** [comment]
Yes, I see it now. Works fine if you use the arrow keys, but dragging the token breaks it.

**Comment by caewok** [comment]
Fixed in v0.6.5.
