### ISSUE TITLE
Support for `Wall Height`

### ISSUE THREAD

**Issue by Aedif** [caewok/fvtt-walled-templates#39]
It would be lovely if template blocking could play nice with the Wall Height module. At the moment templates go completely through walls that have height assigned to them:

https://github.com/caewok/fvtt-walled-templates/assets/7693704/261c4503-62b3-4667-a592-81a29945a7d1

```
Foundry Virtual Tabletop: Version 11 Stable, 11.307
Game System: dnd5e, 2.2.2
Wall Height, 5.0.2
Walled Templates, 0.6.4
```

**Comment by caewok** [comment]
Fixed in v0.6.5. Right now, it is just forcing Wall Height to consider the wall blocking for the template at all heights. A more complex question is whether there is an easy / performant way to consider the 3d template area vs a limited height wall. I will think about that some more.
