### ISSUE TITLE
[Bug/Feature Request?] not correctly truncating templates in PF2e

### ISSUE THREAD

**Issue by esheyw** [caewok/fvtt-walled-templates#4]
https://i.imgur.com/SmtvKHp.png this is a circle template, in pf2e using the default 'burst' rules. You can see the template edge(?) is being properly constrained, but the grid space selection is still acting like before.

**Comment by caewok** [comment]
Is this still happening in version 0.2.3? Below is a similar setup in 5e where the circle template is inside the building and shoots out the door. Just in case, also please make sure that "Blocked by walls" is checked in the template config. 

![Screen Shot 2022-05-11 at 4 12 09 PM](https://user-images.githubusercontent.com/1267134/167962225-1e81dbb6-da44-4329-89e9-97961c3b3a9c.jpg)

I will leave open for now, and if it is still an issue, I can see if there is something different about pf2e that could be causing it.

**Comment by esheyw** [comment]
Can confirm I'm on 0.2.3, PF2E 3.9.2(latest): https://gfycat.com/serpentinedistortedballpython

**Comment by esheyw** [comment]
Rectangle and Ray work correctly, Cone and Circle do not

**Comment by caewok** [comment]
Thanks for that. I see the issue—Pathfinder [ignores the created shape](https://gitlab.com/hooking/foundry-vtt---pathfinder-2e/-/blob/master/src/module/canvas/measured-template.ts) for cone and circle and does its own thing for highlighting the underlying grid. In other words, Pathfinder assumes that it is getting a cone but never checks that. Not Immediately obvious how to fix it—I think I need to dig into the Pathfinder rules and override what the pathfinder system is doing. I can easily skip what Pathfinder is doing, but I would want to try to replicate the rule so it is consistent with the Pathfinder default.

Similar issue to #5 in that DF Template Enhancement also ignores the shape passed to it and does its own thing for grid highlighting.

**Comment by esheyw** [comment]
Yea, I guess the [pf2e area rules](https://2e.aonprd.com/Images/Rules/Rules354.png) don't line up with foundry basics exactly. If you can manage a workaround that'd be excellent; I'll probably keep this active anyway since it works partially, giving the new template outline, even if that can be hard to see. 

Also being compatible with DF Templates would be glorious, but since that module *also* [isn't playing well](https://github.com/flamewave000/dragonflagon-fvtt/issues/365) with PF2e templates right now, not at the top of my wishlist.

**Comment by caewok** [comment]
Should be fixed in v0.2.5. As for DF Templates, I added an issue ticket to DF Templates. Not sure I can fix compatibility just at my end; I think DF Templates would need some modifications.
