### ISSUE TITLE
Investigate possible Drag Ruler issue

### ISSUE THREAD

**Issue by caewok** [caewok/fvtt-walled-templates#47]
https://ptb.discord.com/channels/915186263609454632/1107502968179273778/1144293963356975113

**Comment by YenBenGrey** [comment]
I have also put an issue in on the Drag Ruler github too, however I don't think they are as active at the moment. 
Here is a screenshot of it happening after I have upgraded Foundry and DND5e to the latest software, whether that is relevant or not. 

<img width="523" alt="Screenshot 2023-08-25 at 10 50 20" src="https://github.com/caewok/fvtt-walled-templates/assets/98095856/2dfb6f4b-136a-4996-8778-23006369f60d">

**Comment by caewok** [comment]
Does this still occur in Walled Templates v0.6.7?

**Comment by caewok** [comment]
Answer: Yes. https://ptb.discord.com/channels/915186263609454632/1107502968179273778/1149661062405300234

**Comment by caewok** [comment]
Left a comment in the open drag ruler issue here: https://github.com/manuelVo/foundryvtt-drag-ruler/issues/297. Will likely require a Drag Ruler solution.

**Comment by caewok** [comment]
Temporary work-around that will allow a token with attached template to be dragged (will display movement history incorrectly):

In `Data/modules/drag-ruler/src/main.js`, add a line to the `onEntityLeftDragStart` function to return early if the entity is an attached template:
```js
if ( this.attachedToken ) return; // (Walled Templates) template has attached token.
```

Add it here:
```js
function onEntityLeftDragStart(wrapped, event) {
	wrapped(event);
	if ( this.attachedToken ) return; // (Walled Templates) template has attached token.

	const isToken = this instanceof Token;
	const ruler = canvas.controls.ruler;
	ruler.draggedEntity = this;
	const entityCenter = getEntityCenter(this);
	ruler.rulerOffset = {
		x: entityCenter.x - event.interactionData.origin.x,
		y: entityCenter.y - event.interactionData.origin.y,
	};
	if (game.settings.get(settingsKey, "autoStartMeasurement")) {
		let options = {};
		setSnapParameterOnOptions(ruler, options);
		ruler.dragRulerStart(options, false);
	}
}
```

**Comment by caewok** [comment]
Not fixing Drag Ruler issues. See my Elevation Ruler template for an alternative.
