### ISSUE TITLE
Possible issue with highlighting squares outside the template

### ISSUE THREAD

**Issue by caewok** [caewok/fvtt-walled-templates#48]
https://discord.com/channels/915186263609454632/1107502968179273778/1144339137877524652

**Comment by YenBenGrey** [comment]
Hello there, here is my contribution to the problem, again not sure if it helps at all but no matter what setting I set in Walled Templates I do not get the ideal cone measurement that you get if you do not have WT active.
Here are screenshots.
I have got ALL other modules turned off, and then in the ideal version no modules at all. 

I do apologise if you already know this is the issue, however I just thought it might help :-)

**Comment by YenBenGrey** [comment]
This is with just WT on.....doesn't matter what settings in the WT setting. 
<img width="286" alt="Screenshot 2023-08-26 at 13 26 43" src="https://github.com/caewok/fvtt-walled-templates/assets/98095856/35cc4107-906e-4ea6-9a8a-6ca36345f82c">

**Comment by YenBenGrey** [comment]
This is with no modules on at all......
<img width="345" alt="Screenshot 2023-08-26 at 13 28 35" src="https://github.com/caewok/fvtt-walled-templates/assets/98095856/5f4021d4-5b38-48cf-9896-a523d5b62195">

**Comment by caewok** [comment]
The highlighted squares look the same to me in both screenshots. I can see the template border is missing—is that the issue?

**Comment by YenBenGrey** [comment]
The squares are fine it is the template border that is the issue. That is what I thought this issue was regarding.

**Comment by caewok** [comment]
Fixed in v0.6.7. (There was already an issue open about the border.) Thanks!
