### ISSUE TITLE
Lost compatibility with the Token Magic FX effects

### ISSUE THREAD

**Issue by remyke** [caewok/fvtt-walled-templates#49]
I use libwrapper, Token Magic FX both the lates and I am aware of the fact Token Magic FX does not support the foundryvtt 11 fully yet and my foundry version is the latest.

Between getting foundry vt 11.307->11.308 and Walled template 0.6.4->0.6.6 I lost the ability to cover the template with Token Magic FX effect like Shock. I use Walled template to autotarget and handle the token attachement. 

I can get back a static TMFX effect by changing all the colors in the template and effect, but it is not moving/rotating with the template.
It is possible your change did not effect this, but as you know more about this I ask your opinion if one of your bugfix could cause this. I could not downgrade to 0.6.4 but 0.6.2 and the atachement is not working there.

**Comment by remyke** [comment]
I downgraded to Walled template 0.6.2 now and use Token Attacher to bind the token centered magic area and effect, thus I have workaround, but something went sideways here. I would appreciate any insight.

**Comment by jacksands** [comment]
same issue
