### ISSUE TITLE
[Feature request] Compatibility with DF Template Enhancement

### ISSUE THREAD

**Issue by lucaspicerni** [caewok/fvtt-walled-templates#5]
The module is not compatible with [DF Template Enhancements](https://github.com/flamewave000/dragonflagon-fvtt/tree/master/df-templates):

https://user-images.githubusercontent.com/95550238/167911388-b1e3b7af-7eb4-46b2-a9ab-044d477f4249.mp4

![image](https://user-images.githubusercontent.com/95550238/167911625-018e606a-a79f-41cc-a8da-afbe9b29e346.png)

My settings with DFTE:

![image](https://user-images.githubusercontent.com/95550238/167911831-2cb4ce83-0caf-4b61-ab5b-9e05fadffc65.png)

![image](https://user-images.githubusercontent.com/95550238/167911884-8a5d2dea-e36a-4d1b-8a5e-9ee252fff490.png)

Could you please implement compatibility between them? Thank you!

**Comment by caewok** [comment]
I doubt I can make these two modules compatible without assistance from the DF Template Enhancement author. But in v0.3.0 of Walled Templates, I implemented token autotargeting. Hopefully this will provide a decent work-around to some of DF Template Enhancement's functionality. Feel free to add additional issues if there is something else that DF Template Enhancement does that is critical to your campaign. 

I will leave this issue open for now, pending whether I can work with the DF Template Enhancement author to improve compatibility.

**Comment by dineshm72** [comment]
The primary features that I use in DF Templates which are not supported here are:
* Snap to grid intersections  - dmg specifies this as the way to place AoEs

* dnd5e autotargeting - essentially a mix of the targeting options you currently support.  circles should target based on "If an area of effect is circular and covers at least half a square, it affects that square", but centerpoint can also do in a pinch I guess.  Then all other template shapes should target if any part of the template overlaps the token footprint.  When combined with the snap to grid above, this prevents players from cheesing extra area of effect by dropping templates slightly offset from a corner.

**Comment by LukasPrism** [comment]
It does appear to be snapping for me.

What doesn't appear to be working in v11 is the highlighting.

Even with this setting on 0, half the square still needs to be in the template bounds for it to highlight:
<img width="488" alt="Screenshot 2023-07-03 at 7 37 58 PM" src="https://github.com/caewok/fvtt-walled-templates/assets/104886594/751363d1-cf16-4a76-9e26-a27648a93ca0">
<img width="243" alt="Screenshot 2023-07-03 at 7 47 38 PM" src="https://github.com/caewok/fvtt-walled-templates/assets/104886594/98bb1d06-8ade-4527-a41e-d3e5a93ab226">

**Comment by dineshm72** [comment]
I talked to Lukas about this - I am pretty sure both the items I mentioned above are still issues.  The spells are not snapping to grid corners, and if you set autotargeting to "token area overlaps templates" it will do so, even for circle templates (which by dnd RAW should be "over 50% covered").

I also am not getting any template highlighting at all, but that may be more a settings issue I need to look into.  

Apologies for the very dark pic:
![image](https://github.com/caewok/fvtt-walled-templates/assets/2231877/e9583c6b-7574-4cec-92e3-911412828b1c)

**Comment by dineshm72** [comment]
For reference, here is what I would consider a perfect implementation:
![image](https://github.com/caewok/fvtt-walled-templates/assets/2231877/c7058293-183e-41e4-8bc7-4a047ab52796)

To get this, I have walled templates set to reflect/spread, but not to autotarget.  
![image](https://github.com/caewok/fvtt-walled-templates/assets/2231877/61f62449-89af-4a49-8fc8-dd446fe2c1be)

DF Templates is set to autotarget on a 50% point grid (for circles), and touch (for other templates):
![image](https://github.com/caewok/fvtt-walled-templates/assets/2231877/04e52bee-c7d2-4a7e-aeca-00db396a1efd)

And midi is set to use DF:
![image](https://github.com/caewok/fvtt-walled-templates/assets/2231877/3c5b4361-587f-4577-9f09-699acf5f4fb6)


Ideally, walled templates could implement the above and I could turn off DF (especially since the above is apparently not going to be usable in v11).

**Comment by dineshm72** [comment]
Hmm, possibly it's not working as perfectly as I thought.  DF seems to target things through some walls even when WT is set for "blocked by walls" (as in this cone example):
![image](https://github.com/caewok/fvtt-walled-templates/assets/2231877/74b62c6a-6d98-43d2-81fa-082e4371c8e0)

**Comment by caewok** [comment]
I don't think DF Template Enhancements is getting updated for v11 or beyond, so closing this.

**Comment by DivertedCircle** [comment]
DF Template Enhancements was updated for v12. Is this worth revisiting?
