### ISSUE TITLE
Template borders not rendering

### ISSUE THREAD

**Issue by DeimosJ** [caewok/fvtt-walled-templates#51]
Foundry version: 11.308
Walled Version: 0.6.6
Tested with all other mods disabled, issue persists.

With Walled Templates module enabled the border of templates do not render correctly:
- When placing the template there is no border.
- After changing the border color for the template, the border sometimes appears, this is very erratic though and it disappears when you move the template around. While the template renders the correct squares, the border ignores walls (see attached image).
- If "Hide template border" is enabled, the border renders correctly (on hover) as expected.

No border rendered when created: https://pasteboard.co/yFOPgSUDf6vR.png
Border passing through walls: https://pasteboard.co/LDB9DKbrMiA8.png

**Comment by caewok** [comment]
Fixed in v0.6.7.
