### ISSUE TITLE
Square Templates don't show Sequencer/Automated Animations

### ISSUE THREAD

**Issue by ctbritt** [caewok/fvtt-walled-templates#58]
the square template is not showing animations, either from Sequencer or Automated Animations. It does work for non-square templates, though. 

![CleanShot 2023-09-07 at 16 09 15@2x](https://github.com/caewok/fvtt-walled-templates/assets/4516034/3f3199ad-6bde-4f01-88ab-cb19de6003f1)

Sequencer recognizes the animations are there as you can see here: 
![CleanShot 2023-09-07 at 16 11 39@2x](https://github.com/caewok/fvtt-walled-templates/assets/4516034/ba5eac82-1979-4da8-b50d-921a9d8230c4)

but they're not displaying when Walled Templates is active. 

Foundry 11.308
DnD 2.3.1
Walled Templates 0.6.7
Sequencer: 3.1.4

**Comment by caewok** [comment]
They do appear for me, so something seems to be specific to your setup. 
1. What are your settings for "Default Shape Settings" for squares?
2. What are your settings for the spell you are casting?

**Comment by caewok** [comment]
Possibly related: https://ptb.discord.com/channels/915186263609454632/1107502968179273778/1149800158805098540

**Comment by caewok** [comment]
Should be fixed in v0.6.8. Thanks for the screenshots and info! That helped narrow it down.
