### ISSUE TITLE
Template doesn't appears and game freeze

### ISSUE THREAD

**Issue by OzBezerius** [caewok/fvtt-walled-templates#63]
Foundry: 11.305
D&D: 2.3.1
Walled Templates: 0.6.8
Midi QOL: 11.0.17

This only happens in one of my games, I have tried in other with the exact same configuration for all the modules and it worked correctly. I am using the forge to host the game.
This error message pop out every time, even whit the option selected correctly.
![image](https://github.com/caewok/fvtt-walled-templates/assets/25015102/53cfa9e1-5797-41d0-a01c-6e1ba5d16a04)
Console log:
![image](https://github.com/caewok/fvtt-walled-templates/assets/25015102/6b13c64a-156f-458e-a0b3-fbe36319879f)

**Comment by caewok** [comment]
You need to update your Foundry version to v11.308. (That is mentioned in the pop-up that first appears when you update Walled Templates.)
