### ISSUE TITLE
Compatibility with Wall Height / Levels.

### ISSUE THREAD

**Issue by Ikabodo** [caewok/fvtt-walled-templates#66]
The current implementation of Walled Templates forces the template to consider walls of all heights, regardless of height. This works for some cases. 

But it causes a direct incompatibility with Wall Height and especially with Levels. On a map with different walls on different levels the template will merge all walls and apply to that.

![image](https://github.com/caewok/fvtt-walled-templates/assets/7766890/82541fe5-c47b-4cc4-897b-c04b086d3f12)

I assume this was a fix based on this:
https://github.com/caewok/fvtt-walled-templates/issues/39

Perhaps its possible to only consider walls with the same wall-height as the template?
![image](https://github.com/caewok/fvtt-walled-templates/assets/7766890/8acb7c86-efbc-48e6-b994-4e1cb859d37d)

(3d support seems complicated, so that's not what I am talking about here. Just wall height)

**Comment by caewok** [comment]
Fixed in v0.7.8. Template height for purposes of Wall Height module set to the template elevation.

**Comment by caewok** [comment]
More fixes in v0.7.9
