### ISSUE TITLE
Constantly re-targets tokens inside a template.

### ISSUE THREAD

**Issue by GambetTV** [caewok/fvtt-walled-templates#7]
If a player uses an ability that targets tokens within a template, for some reason this module causes the template to re-target tokens every time you load into a map with that template, or even so much as switch to the Measurement Controls in the UI. So for instance I might only want the thing to target a couple of tokens, and it automatically targets all of them, which is fine, but then I untarget the ones I don't want. But then if I touch the Measurement Controls at all, it'll just retarget everyone again.

**Comment by caewok** [comment]
I get what you are saying; that is sort of the intended function of the autotargeting. Could you elaborate a bit on a use case where it is important to draw the template, move back to the token controls to de-target, and then go back to the template? 

I am just trying to figure out what would make sense as the alternative here. I was thinking that maybe once the template is placed, it does not try to re-target unless moved. As you say, right now it re-targets when switching back to the template controls or when re-loading a scene.

**Comment by caewok** [comment]
In the meantime, you can alleviate some of this issue if you select "Display toggle button" in the Walled Templates settings for "enable autotargeting." If you do that, a target icon will appear in the template controls on the left of the screen. If you de-select that, it will stop autotargeting. So, for example, you could set a template with autotargeting. Then hit that button and switch to the token control to de-target one or more tokens. So long as that button is de-selected, the autotargeting should not resume.

**Comment by caewok** [comment]
Should be mostly fixed by a combination of the above "Display toggle button" and the changes I implemented in v0.3.3. 

If you have a specific workflow that still doesn't work with these adjustments, please re-open with further explanation and I will see what I can do! Thanks!
