### ISSUE TITLE
[Request?] Russian Translation module compatibility 

### ISSUE THREAD

**Issue by SilvesTheRog** [caewok/fvtt-walled-templates#73]
Hello!
This module is wonderful, but for some reason, the walled templates settings inside the spells won't work with the Russian Translation module (https://foundryvtt.com/packages/ru-ru). Choosing Russian in FVTT language preference does nothing, so we have to use the module instead. Enabling it causes the walled templates to disappear from the spell's details tab. 

The 1st screenshot shows FVTT set to Russian with Russian Translation module **enabled**. 
The 2nd screenshot shows FVTT set to Russian with Russian Translation module **disabled**. As you can see, the walled templates settings are there. All the other module's features work as intended, by the way.

Not sure if this request belongs here or on the translation's git, but I will appreciate any help.

![image](https://github.com/caewok/fvtt-walled-templates/assets/127493227/1ad0ee21-3d40-479e-8dec-485225e55caa)
![image](https://github.com/caewok/fvtt-walled-templates/assets/127493227/b1d27ae3-53b7-443d-9e20-183f513dc13d)

**Comment by caewok** [comment]
It looks like updates to Foundry or dnd5e may have fixed this? I can now see the Walled Templates section where before I could not. 

If you want Russian translation of the Walled Templates part, the way to do it is to give me a translation of [this `en.json` file](https://github.com/caewok/fvtt-walled-templates/blob/main/languages/en.json). Either submit a PR or open a Git issue and paste in the translation.
