### ISSUE TITLE
Console error "Update To Hook"

### ISSUE THREAD

**Issue by Dyrnwyrm** [caewok/fvtt-walled-templates#76]
Got this error for some reason, dunno why

DnD 2.4.0
Foundry 11.315

![image](https://github.com/caewok/fvtt-walled-templates/assets/129613553/6ecb5e6e-9a1f-4cea-bc4a-6b65e9932a84)

**Comment by Dyrnwyrm** [comment]
It started happening before the 2.4 update at random, i tried nuking all my tokens so Midi Protection comes in but nothing so im not sure about the cause,  it happens while tokens are moving, not even casting a spell or something.

**Comment by Dyrnwyrm** [comment]
Actives Auras fixes this issue, issue related to moving a token on a scene that the GM is not looking, Rideable got fixed too by using the recommended routinglib configuration.

**Comment by caewok** [comment]
Should be fixed in v0.7.1.
