### ISSUE TITLE
Snap to grid weirdness

### ISSUE THREAD

**Issue by caewok** [caewok/fvtt-walled-templates#81]
https://discord.com/channels/915186263609454632/1167221795103985764/1192294259114655794

**Comment by caewok** [comment]
When casting a spell (e.g. _fireball_) in dnd5e, the template preview does not use `MeasuredTemplate.prototype._onDragLeftMove`. It doesn't seem to be using the `AbilityTemplate` version either. So I need to determine how to change the template preview drag left move method, wherever that is getting called.

**Comment by Zamrod** [comment]
I'm fairly certain that is contained somewhere in here: https://github.com/foundryvtt/dnd5e/blob/master/module/canvas/ability-template.mjs

**Comment by caewok** [comment]
You were correct! I ended up doing a mixed wrap for `AbilityTemplate.prototype._onMovePlacement` to force snapping in the preview. Fixed in v0.7.2. Thanks!

(The move timeout plus the refresh made it impractical to just wrap the method.)
