### ISSUE TITLE
Walled Templates truncates measured templates on Hex Grids

### ISSUE THREAD

**Issue by KKDavion** [caewok/fvtt-walled-templates#9]
As above. Find the Culprit! was used to determine that Walled Templates on its own causes this issue.

This is the current behaviour with Walled Templates on a Hexagonal Columns (Odd) gridded map, but any hexagonal grid will reproduce this issue.
![3ae6a51ac8c2185bacc4410ffd640d9d](https://user-images.githubusercontent.com/32150450/174410918-8691496a-af15-4e77-81c1-f2df5318a2f4.png)

This is the expected behaviour when walled templates is disabled. Notice that in all cases, at least one row on one side of the template is missing hexes in the above image. No settings within the module itself seem to resolve this issue, so unfortunately this renders the module unusable for me.
![de4ccd74b2debd51f739e26a7e16d1f4](https://user-images.githubusercontent.com/32150450/174410969-db1684db-b05f-436a-adb0-0d0fab4ebc8d.png)

Any further input would be appreciated.

**Comment by caewok** [comment]
What system are you using?

**Comment by caewok** [comment]
I fixed the truncation issue in v0.3.4. There are still limited instances where Foundry and Walled Templates can differ slightly. When the circle crosses the center point of the hex, I am finding it difficult to precisely replicate what Foundry is doing for its inclusion test. I also don't love how the Foundry version is unbalanced in those cases. 

Closing this for now, but please feel free to file a new issue if you have a specific use case in mind that the improvements in v0.3.4 did not address.
